const MNIST_IMAGE_SIZE = 28;
const MNIST_PIXEL_COUNT = MNIST_IMAGE_SIZE * MNIST_IMAGE_SIZE;

const MNIST_NB_CLASSES = 10;

module.exports = {
    MNIST_IMAGE_SIZE,
    MNIST_PIXEL_COUNT,
    MNIST_NB_CLASSES
};